name: Daily Auto Commit

on:
  schedule:
    # Runs daily at 9:00 AM EST (5 hours behind 2:00 PM UTC)
    - cron: "0 14 * * *"
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Daily Commit Script
        run: |
          chmod +x ./daily_commit.sh
          ./daily_commit.sh

      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
          directory: "."
